### PR TITLE
in-progress with trad. chinese (tw) translation

### PR DESCRIPTION
**Pull request by chelseaw2525**
> began translation chinese translation for taiwan region (traditional characters)
> to-do: section "special", proofread

### CODE REVIEW

**Comment by kylerchin** [comment]
note to josh: do not merge without my approval

**Comment by kylerchin** [comment]
don't merge without my final review

**Comment by lolpro11** [comment]
I have no involvement over this

**Comment by kylerchin** [comment]
Note to other maintainers: don't merge without my final review

**Comment by lolpro11** [comment]
Thank you for clarifying

**Comment by kylerchin** [comment]
Should I work on conversion to simplified?

Also, would we need a seperate translation for HK Traditional? I'll check the characters in the morning

**Comment by chelseaw2525** [comment]
Yeah convert it to simplified and make sure the terms are correct; as you know, mainland uses different terms for some words. HK traditional uses different words for stuff too. I think someone mentioned that they wanted to do HK in the Discord server, maybe check with them?

**Comment by kylerchin** [comment]
Amazing! Thank you!

**Pull request merged**
